sudo: required
services: 
        - docker

before_install:
        - docker build -t satishinturidocker/travis -f Dockerfile.dev .

script: 
        - docker run satishinturidocker/travis npm run test -- --coverage
